name: Deploy

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: false
          lfs: true
          clean: clean
          path: source
      - name: Build blog website
        run: |
          if [ -e "${GITHUB_WORKSPACE}/_v2ray_com" ]; then rm -rf "${GITHUB_WORKSPACE}/_v2ray_com" ; fi
          bash "deploy-v2ray.mdoc.xyz.sh"
      - name: Deploy blog website
        run: |
          mkdir -p $HOME/.ssh
          chmod 700 $HOME/.ssh
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > $HOME/.ssh/id_rsa.action
          chmod 600 $HOME/.ssh/id_rsa.action
          echo "v2ray.mdoc.xyz" > "${GITHUB_WORKSPACE}/_v2ray_com/CNAME"
          rsync -rlptDvz -e "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o User=v2ray -o IdentityFile=$HOME/.ssh/id_rsa.action -o Port=36000" "${GITHUB_WORKSPACE}/_v2ray_com" v2ray@vr-h.ouri.app:/home/website/v2ray-doc
          echo "${GITHUB_SHA} was successfully deployed"
